---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: aarkay-read-role
  namespace: aarkay
rules: 
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["get","list","watch"]   

---
apiVersion: rbac.authorization.k8s.io
kind: RoleBinding
metadata: 
  name: aarkay-read-rolebinding
  namespace: aarkay
roleRef:
  kind: Role
  name: aarkay-read-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: aarkay
  apiGroup: rbac.authorization.k8s.io  