---
apiVersion: rbac.authorization.k8s.io
kind: Role
metadata: 
  name: aarkay-developer
  namespace: aarkay
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["deployments","services","secrets","configmaps"]
    verbs: ["get","list","watch","create","update","delete"]  
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: aarkay
  name: aarkay-developer-rolebinding
roleRef: 
  name: aarkay-developer
  kind: Role
  apiGroup: rbac.authorization.k8s.io  
subjects:
  - name: rajkumar
    kind: User
    apiGroup: rbac.authorization.k8s.io