---
apiVersion: v1 
kind: Namespace 
metadata: 
  name: aarkay
  labels:
    name: aarkay

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: aarkay
  namespace: aarkay-admin-Role
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]    

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: aarkay-admin-RoleBinding
  namespace: aarkay
roleRef:
  name: aarkay-admin-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io/v1
subjects:
  - name: aarkay-aarkay-admin-Role
    kind: User
    apiGroup: rbac.authorization.k8s.io  
